config/routes.rb
Magpie::Application.routes.draw do
  resources :users, only: [:show, :new, :create]
  match '/signup' => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy'

  resources :lists, only: [:index, :show, :new, :create]

  root to: redirect('/signup')
end

app/models/item.rb
class Item
  attr_reader :name
  attr_accessor :url, :price, :sale, :photos

  def initialize(attrs = {})
    @name = attrs[:name]
    @url = attrs[:url] ? attrs[:url] : nil
    @price = attrs[:price] ? attrs[:price] : 0
    @sale = attrs[:sale] ? attrs[:sale] : false
    @photos = attrs[:photos] ? attrs[:photos] : []
  end
end

app/models/photo.rb
class Photo
  attr_reader :url

  def initialize(url)
    @url = url
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :wishlists

  attr_accessible :email, :password, :password_confirmation, :username, :name

  validates :email,     :presence => true,
                        :uniqueness => true,
                        :format => { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/  }
  validates :username,  :presence => true,
                        :uniqueness => true
  validates :password,  :presence => true, if: :password,
                        :confirmation => true, if: :password
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user

  attr_accessible :item_count, :name, :user_id

  validates :name, :presence => true
  validates :user, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :require_login

  def index
    @lists = Wishlist.order 'name'
    render 'empty' and return if @lists.empty?
  end

  def show
    @lists = Wishlist.order 'name'
    @list = Wishlist.find params[:id]
  end

  def new
    @list = Wishlist.new
  end

  def create
    @list = Wishlist.create params[:wishlist].merge(user_id: current_user.id)
    render :new and return unless @list.valid?
    redirect_to list_path @list
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = login params[:user][:email], params[:user][:password]
    unless @user
      @user = User.new
      flash[:error] = 'Invalid email or password'
      render :new and return
    end
    redirect_to lists_path, notice: "Welcome #{@user.name}"
  end

  def destroy
    logout
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, only: :show

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create params[:user]
    render :new and return unless @user.valid?
    auto_login @user
    redirect_to user_path @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class='header-content'>
  <div class='left'>
    <%= link_to image_tag('birdhouse-with-text.png'), lists_path %>
  </div>

  <div class='right authentication'>
    <% if logged_in? %>
      <div class='profile'>
        <div class='left'>
          <%= link_to image_tag('empty-profile.png'), user_path(current_user) %>
        </div>
        <div class='left profile-name'>
          <%= link_to current_user.name, user_path(current_user) %>
          <div class='signout'><%= link_to 'Sign Out', signout_path %></div>
        </div>
      </div>
    <% elsif params[:controller] == 'sessions' %>
      <%= link_to 'Sign Up', signup_path %>
    <% else %>
      <%= link_to 'Sign In', signin_path %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magpie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'layouts/header' %>

<% if flash[:notice] %>
  <div class='notice'>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class='error'>
    <%= flash[:error] %>
  </div>
<% end %>

<div class='body-content'>
  <%= yield %>
</div>

</body>
</html>

app/views/lists/_list.html.erb
<div class='span-5'>
  <h2>Lists</h2> 
  <ul>
    <% @lists.each do |list| %>
      <li>
      <a href="<%= list_path(list) %>" class="<%= 'active' if @list && @list == list %>">
          <%= list.name %>
          <span class='count'><%= list.item_count %></span>
        </a>
      </li>
    <% end %>
    <li>
      <%= link_to "Add List", new_list_path %>
    </li>
  </ul>
</div>

app/views/lists/empty.html.erb
<div class='empty container'>
  <div class='push-5 span-14'>
    <h1>You currently do not have any wish lists</h1>
    <div class='clear padded'>
      <%= link_to "+ Add a list", new_list_path, class: 'btn' %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class='list-index-content container'>
  <%= render partial: 'list' %>

  <div class='span-14 welcome'>
    <h1>Welcome!</h1>
    <h5> Go ahead, start adding lists</h5>
    <%= image_tag 'left-arrow.png' %>
  </div>
</div>

app/views/lists/new.html.erb
<div class='new-wishlist-content container'>
  <div class='push-5 span-14'>
    <h1>New List</h1>
    <h5>Go ahead, add your list</h5>

    <% if @list.errors.any? %>
      <div class='error'>
        <ul>
          <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for @list, url: lists_path do |f| %>
      <div class='field full'>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class='actions clear'>
        <%= f.submit %>
      </div>

    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class='list-show-content container'>
  <%= render partial: 'list' %>

  <div class='span-14'>
    <h1><%= @list.name %></h1>
  </div>
</div>

app/views/users/new.html.erb
<div class='signup-content container'>
  <div class='push-5 span-14'>
    <h1>Sign Up!</h1>
    <h5>It's quick, easy and free</h5>

    <% if @user.errors.any? %>
      <div class='error'>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for @user do |f| %>
      <div class='field full'>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>

      <div class='field full'>
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>

      <div class='field inline half'>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>

      <div class='field inline last half'>
        <%= f.label :password_confirmation, 'Re-enter password' %>
        <%= f.password_field :password_confirmation %>
      </div>

      <div class='actions clear'>
        <%= f.submit 'Sign Up' %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='user-show-content container'>

  <div class='push-5 span-14 display'>
    <h1><%= @user.name %></h1>
    <h5><%= @user.username %></h5>

    <label>Email</label>
    <div class='field'><%= @user.email %></div>
  </div>
</div>